import "@styles/globals.css";

import { cn } from "@lib";
import type { Metadata } from "next";
import { Navbar } from "@components";
import { Toaster } from "@ui/toaster";
import { Inter } from "next/font/google";
import { Separator } from "@ui/separator";
import { ClerkProvider, ThemeProvider } from "@providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{ colorScheme: "dark" }}
      className={cn(inter.className, "dark")}
    >
      <body>
        <ThemeProvider>
          <ClerkProvider>
            <div className="flex h-[100svh] flex-col w-[100svw] items-center dark:bg-black overflow-hidden">
              <Navbar />
              <Separator />
              <main className="flex h-full w-full justify-center items-center dark:bg-neutral-900 overflow-x-hidden overflow-y-auto">
                {children}
              </main>
            </div>

            <Toaster />
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
